export type Cliente = {
  senha: string
  acesso_automatico_central: string
  alterar_senha_primeiro_acesso: string
  senha_hotsite_md5: string
  indicado_por: string
  ativo: string
  id: string
  grau_satisfacao: string
  razao: string
  fantasia: string
  cnpj_cpf: string
  ie_identidade: string
  data_cadastro: string
  uf: string
  crm: string
  endereco: string
  cidade: string
  cond_pagamento: string
  bairro: string
  fone: string
  numero: string
  cep: string
  filial_id: string
  contato: string
  latitude: string
  longitude: string
  id_conta: string
  hotsite_email: string
  email: string
  obs: string
  id_tipo_cliente: string
  id_candato_tipo: string
  tipo_pessoa: string
  telefone_comercial: string
  telefone_celular: string
  referencia: string
  complemento: string
  id_condominio: string
  ramal: string
  data_nascimento: string
  participa_cobranca: string
  num_dias_cob: string
  tabela_preco: string
  id_vendedor: string
  bloco: string
  isuf: string
  apartamento: string
  tipo_assinante: string
  idx: string
  skype: string
  whatsapp: string
  id_perfil: string
  id_concorrente: string
  hotsite_acesso: string
  responsavel: string
  status_prospeccao: string
  estado_civil: string
  crm_data_vencemos: string
  ativo_serasa: string
  iss_classificacao_padrao: string
  rg_orgao_emissor: string
  ultima_atualizacao: string
  nacionalidade: string
  deb_automatico: string
  deb_agencia: string
  deb_conta: string
  alerta: string
  endereco_cob: string
  numero_cob: string
  bairro_cob: string
  cidade_cob: string
  uf_cob: string
  cep_cob: string
  referencia_cob: string
  complemento_cob: string
  profissao: string
  id_operadora_celular: string
  participa_pre_cobranca: string
  cob_envia_email: string
  cob_envia_sms: string
  contribuinte_icms: string
  Sexo: string
  nome_pai: string
  nome_mae: string
  quantidade_dependentes: string
  nome_conjuge: string
  fone_conjuge: string
  cpf_conjuge: string
  rg_conjuge: string
  data_nascimento_conjuge: string
  moradia: string
  nome_contador: string
  telefone_contador: string
  ref_com_empresa1: string
  ref_com_empresa2: string
  ref_com_fone1: string
  ref_com_fone2: string
  ref_pes_nome1: string
  ref_pes_nome2: string
  ref_pes_fone1: string
  ref_pes_fone2: string
  emp_empresa: string
  emp_cnpj: string
  emp_cep: string
  emp_endereco: string
  emp_cidade: string
  emp_fone: string
  emp_cargo: string
  emp_remuneracao: string
  emp_data_admissao: string
  website: string
  orgao_publico: string
  pipe_id_organizacao: string
  im: string
  cif: string
  tipo_cliente_scm: string
  pis_retem: string
  cofins_retem: string
  csll_retem: string
  irrf_retem: string
  nascimento_mae: string
  nascimento_pai: string
  identidade_mae: string
  identidade_pai: string
  cpf_mae: string
  cpf_pai: string
  inscricao_municipal: string
  nome_representante_1: string
  nome_representante_2: string
  cpf_representante_1: string
  cpf_representante_2: string
  identidade_representante_1: string
  identidade_representante_2: string
  codigo_operacao: string
  convert_cliente_forn: string
  tipo_pessoa_titular_conta: string
  cnpj_cpf_titular_conta: string
  crm_data_perdemos: string
  crm_data_sem_viabilidade: string
  crm_data_sem_porta_disponivel: string
  crm_data_abortamos: string
  crm_data_negociando: string
  crm_data_apresentando: string
  crm_data_sondagem: string
  crm_data_novo: string
  atualizar_cadastro_galaxPay: string
  foto_cartao: string
  cli_desconta_iss_retido_total: string
  cidade_naturalidade: string
  cadastrado_via_viabilidade: string
  tipo_localidade: string
  facebook: string
  id_campanha: string
  desconto_irrf_valor_inferior: string
  filtra_filial: string
}
