export type FnAReceber = {
  id_remessa: string
  gateway_link: string
  nn_boleto: string
  boleto: string
  data_inicial: string
  data_final: string
  id: string
  liberado: string
  filial_id: string
  status: string
  data_emissao: string
  data_vencimento: string
  valor: string
  obs: string
  valor_recebido: string
  valor_aberto: string
  id_cliente: string
  pagamento_valor: string
  pagamento_data: string
  id_carteira_cobranca: string
  credito_data: string
  baixa_data: string
  numero_parcela_recorrente: string
  documento: string
  id_saida: string
  tipo_recebimento: string
  tipo_renegociacao: string
  valor_cancelado: string
  data_cancelamento: string
  id_mot_cancelamento: string
  id_renegociacao: string
  id_cobranca: string
  previsao: string
  id_renegociacao_novo: string
  libera_periodo: string
  impresso: string
  forma_recebimento: string
  arquivo_remessa_baixado: string
  nparcela: string
  id_nota_gerada_opc4: string
  status_cobranca: string
  tipo_cobranca: string
  id_contrato_principal: string
  id_contrato_avulso: string
  id_contrato: string
  id_nota_gerada: string
  id_im_imovel: string
  parcela_proporcional: string
  linha_digitavel: string
  duplicata: string
  tipo_pagamento_cartao: string
  id_sip: string
  titulo_protestado: string
  desconto_condicional_valor: string
  gerencianet_token: string
  validade_desconto_condicional: string
  id_conta: string
  motivo_alteracao: string
  id_remessa_alteracao: string
  cancelamento_id_operador: string
  baixa_id_operador: string
  titulo_importado: string
  origem_importacao: string
  ultima_atualizacao: string
  aguardando_confirmacao_pagamento: string
  parcelado_cartao: string
  pix_txid: string
  id_nota_gerada_opc2: string
  id_nota_gerada_opc3: string
  recebido_via_pix: string
  id_lote_geracao_financeiro_fatura: string
}
