export interface Funcionarios {
  img_assinatura: string
  ramal: string
  envia_telegram_os: string
  telegram_chat_id_funcionario: string
  id_chat_telegram_funcionario: string
  id_perfil_jornada_trabalho: string
  rastreador: string
  ferias_colaborador: string
  id_conta_decimo: string
  id: string
  funcionario: string
  ativo: string
  id_funcao: string
  fone_celular: string
  id_conta: string
  email: string
  coeficiente: string
  cor_mapa: string
  filial_id: string
  data_nascimento: string
  data_admissao: string
  id_conta_salario: string
  envia_email_os: string
  envia_sms_os: string
  integracao_calendario: string
  id_setor_padrao: string
  endereco: string
  cidade: string
  numero: string
  bairro: string
  uf: string
  cep: string
  complemento: string
  referencia: string
  cpf_cnpj: string
  ie_identidade: string
  rg_orgao_emissor: string
  nacionalidade: string
  fone: string
  telefone_comercial: string
  assinatura_email: string
  id_email_smtp: string
  banco: string
  agencia: string
  numero_conta_dv: string
  agencia_dv: string
  conta: string
  tipo_recebimento: string
  data_demissao: string
  obs: string
  percen_max_desc_areceber: string
  prj_custo_hora_adicionais: string
  prj_custo_hora_base: string
  camara_centralizadora: string
  estado_civil: string
  nome_mae: string
  nome_pai: string
  tipo_deficiencia: string
  possui_deficiencia: string
  camiseta: string
  num_manequim: string
  cor_raca: string
  num_dependentes: string
  dependentes_ir: string
  nome_conjuge: string
  estagio_escolaridade: string
  periodo_escolaridade: string
  grau_escolaridade: string
  falar_com: string
  fone_emergencia: string
  salario: string
  cnh_categoria: string
  titulo_secao: string
  titulo_zona: string
  titulo_numero: string
  ctps_cidade_emissao: string
  ctps_data_emissao: string
  ctps_serie: string
  ctps_numero: string
  cnh_numero: string
  cpf_conjuge: string
  rg_conjuge: string
  cnh_vencimento: string
  pis_data: string
  pis_numero: string
  rg_data_emissao: string
  dep_tres_cpf: string
  dep_tres_rg: string
  dep_tres_nome: string
  dep_dois_cpf: string
  dep_dois_rg: string
  dep_dois_nome: string
  dep_um_cpf: string
  dep_um_rg: string
  dep_um_nome: string
  id_departamento: string
  ultima_atualizacao: string
  exibir_colaborador_inmap: string
  tipo_chave_pix: string
  chave_pix: string
}
