export type RadpopRadioClienteFibra = {
  id_projeto: string
  id_contrato: string
  gemport: string
  ip_gerencia: string
  login_onu_cliente: string
  senha_onu_cliente: string
  porta_telnet_onu_cliente: string
  perfil_onu_cliente: string
  script_onu_cliente: string
  senorid: string
  latitude: string
  longitude: string
  endereco_padrao_cliente: string
  id_condominio: string
  bloco: string
  apartamento: string
  cep: string
  endereco: string
  numero: string
  bairro: string
  cidade: string
  referencia: string
  complemento: string
  distancia_onu: string
  vlan_dhcp: string
  vlan_tr69: string
  vlan_iptv: string
  vlan_voip: string
  vlan_pppoe: string
  vlan_outros: string
  id_ramal: string
  id_onu_unms: string
  id_activity: string
  radpop_estrutura: string
  porta_web_onu_cliente: string
  tipo_operacao: string
  id: string
  id_transmissor: string
  nome: string
  id_caixa_ftth: string
  porta_ftth: string
  id_login: string
  onu_numero: string
  service_port: string
  onu_tipo: string
  ponid: string
  mac: string
  comandos: string
  sinal_rx: string
  sinal_tx: string
  temperatura: string
  voltagem: string
  data_sinal: string
  id_perfil: string
  slotno: string
  ponno: string
  tipo_autenticacao: string
  versao: string
  vlan: string
  causa_ultima_queda: string
  id_hardware: string
}
