export type RadpopRadio = {
  login_hw: string
  senha_hw: string
  usa_smart: string
  id_pv_grupo_backup: string
  id_olt: string
  id_servidor_unms: string
  id_olt_unms: string
  id_olt_conscius: string
  perfil_fibra_padrao: string
  id_olt_externo: string
  usa_vpn: string
  id_padrao_cores: string
  operador_neutro: string
  busca_potencia: string
  perfil_neutro_bridge: string
  perfil_neutro_router: string
  timeout: string
  id: string
  ativo: string
  descricao: string
  cor_mapa: string
  fwversion: string
  id_pop: string
  conexoes_ultima: string
  ip: string
  login: string
  senha: string
  porta_ssh: string
  fabricante_modelo: string
  uptime: string
  time: string
  speed_lan: string
  conexoes_ulltima_data: string
  speed_wlan: string
  modelo: string
  cpu_load: string
  total_memory: string
  txrate: string
  free_memory: string
  rxrate: string
  temperatura: string
  voltagem: string
  autosave: string
  httpd_port: string
  current_firmware: string
  upgrade_firmware: string
  porta_telnet: string
  porta_api: string
  ip_anm: string
  gabinete: string
  subrack: string
  porta_telnet_tl1: string
  login_anm: string
  senha_anm: string
  id_prov_snmp: string
}
