export type RadUsuarios = {
  autenticacao_por_mac: string
  relacionar_concentrador_ao_login: string
  agent_circuit_id: string
  pool_radius: string
  id_rad_dns: string
  modelo_tranmissor: string
  auto_preencher_ipv6: string
  fixar_ipv6: string
  relacionar_ipv6_ao_login: string
  ip_aux: string
  porta_aux: string
  id_radgrupos_pools: string
  service_tag_vlan: string
  acct_session_id: string
  senha_rede_sem_fio_5ghz: string
  ssid_router_wifi_5ghz: string
  mtu: string
  onu_compartilhada: string
  id_reserva_rede_neutra: string
  tipo_acesso: string
  usuario_wpa2aes: string
  senha_wpa2aes: string
  id: string
  ativo: string
  online: string
  tipo_conexao_mapa: string
  id_contrato: string
  id_grupo: string
  id_cliente: string
  login: string
  obs: string
  senha: string
  auto_preencher_ip: string
  ip: string
  auto_preencher_mac: string
  pd_ipv6: string
  mac: string
  endereco: string
  numero: string
  complemento: string
  relacionar_ip_ao_login: string
  bairro: string
  relacionar_mac_ao_login: string
  conexao: string
  id_concentrador: string
  latitude: string
  longitude: string
  concentrador: string
  tipo_conexao: string
  ultima_conexao_inicial: string
  ultima_conexao_final: string
  interface: string
  tempo_conectado: string
  franquia_maximo: string
  franquia_consumo: string
  autenticacao: string
  login_simultaneo: string
  senha_md5: string
  fixar_ip: string
  ip_aviso: string
  porta_http: string
  porta_router2: string
  id_transmissor: string
  id_caixa_ftth: string
  ftth_porta: string
  senha_router1: string
  senha_router2: string
  senha_rede_sem_fio: string
  id_porta_transmissor: string
  cliente_tem_a_senha: string
  franquia_atingida: string
  autenticacao_wps: string
  id_df_projeto: string
  autenticacao_mac: string
  motivo_desconexao: string
  autenticacao_wpa: string
  tempo_conexao: string
  tipo_vinculo_plano: string
  count_desconexao: string
  onu_mac: string
  vlan: string
  vlan_ip_rede: string
  id_hardware: string
  id_condominio: string
  tipo_equipamento: string
  metragem_interna: string
  metragem_externa: string
  tronco: string
  splitter: string
  sinal_ultimo_atendimento: string
  interface_transmissao: string
  franquia_consumo_up: string
  endereco_padrao_cliente: string
  cidade: string
  cep: string
  referencia: string
  ssid_router_wifi: string
  bloco: string
  apartamento: string
  usuario_router1: string
  upload_atual: string
  download_atual: string
  gw_vlan: string
  id_filial: string
  ponta: string
  ultima_atualizacao: string
  framed_fixar_ipv6: string
  framed_autopreencher_ipv6: string
  framed_relacionar_ipv6_ao_login: string
  framed_pd_ipv6: string
  lte_id: string
  id_integracao: string
}
