export type SuOSSAssunto = {
  imprimir_prod_serv: string
  modelo_email: string
  wiz_comodato: string
  wiz_produtos: string
  wiz_mensalidade: string
  wiz_arquivos: string
  wiz_localizacao: string
  wiz_autorizar_ONU: string
  wiz_resumo_os: string
  localizacao_obrigatoria_cliente_finalizacao_os: string
  localizacao_obrigatoria_login_finalizacao_os: string
  obrigar_processo_atendimento: string
  id_processo: string
  login_obrigatorio: string
  id_resposta_padrao_finalizacao: string
  mostrar_no_service: string
  id_sms_deslocamento: string
  considerar_sla: string
  id_msg_omnichannel_deslocamento: string
  id: string
  ativo: string
  assunto: string
  su_oss_modelo_impressao: string
  tipo: string
  meta_horas_abertura: string
  tipo_comissao: string
  tipo_cobranca: string
  valor_comissao: string
  id_oss_kit: string
  cor_marcador: string
  layout_impressao: string
  id_tipo_doc_pedido: string
  id_tipo_doc_servico: string
  id_tipo_doc_comodato: string
  finalidade: string
  mostra_hotsite: string
  id_resposta_padrao: string
  formato_endereco: string
  permite_abrir_cliente_atraso: string
  endereco_padrao: string
  numero_de_vias: string
  horario_tempo_assunto: string
  fat_somente_finalizada: string
  meta_horas_agendamento: string
  id_cond_pag_servico: string
  id_cond_pag_produto: string
  sla_apenas_dias_uteis: string
  metas_horas_abertura_ticket: string
  quantidade_fotos_finalizacao_os: string
  exige_fotos_finalizacao_os: string
  diagnostico_obrigatorio_finalizacao_os: string
  wiz_servico: string
  card_data_reservada: string
  id_cond_pag_patrimonio_venda: string
  id_tipo_doc_patrimonio_venda: string
  validar_choque_horarios_agendamento_os: string
  ultima_atualizacao: string
  msg_regiao_manutencao: string
  id_vendedor_faturamento: string
  setor_su_oss_chamado: string
  descricao: string
  equipe_obrigatoria_finalizacao_os: string
  habilitar_mini_projeto: string
  wiz_assinatura_obrig: string
  mesclar_mini_projetos_ao_finalizar_os: string
  id_checklist: string
  wiz_service_mobile_adicionais: string
  wiz_service_mobile_onu: string
  wiz_service_mobile_loc: string
  wiz_service_mobile_anexos: string
  wiz_service_mobile_checklist: string
  wiz_service_mobile_enviar_sms_deslocamento: string
  service_mobile_max_parc_adic_serv: string
  integracao_assinatura_digital: string
  wiz_service_mobile_config_dispositivo: string
  contrato_obrigatorio: string
  quantidade_equipamentos: string
  exige_comodato_finalizar_os: string
  exige_produto_finalizar_os: string
  quantidade_produtos: string
}
