export type SuTicket = {
  id_resposta: string
  latitude: string
  longitude: string
  origem_endereco_estrutura: string
  id: string
  tipo: string
  status_sla: string
  id_cliente: string
  id_assunto: string
  titulo: string
  data_criacao: string
  data_ultima_alteracao: string
  status: string
  su_status: string
  prioridade: string
  id_ticket_setor: string
  mensagens_nao_lida_sup: string
  id_ticket_origem: string
  id_usuarios: string
  mensagens_nao_lida_cli: string
  protocolo: string
  token: string
  id_wfl_processo: string
  id_su_diagnostico: string
  origem_endereco: string
  menssagem: string
  endereco: string
  id_filial: string
  id_responsavel_tecnico: string
  interacao_pendente: string
  id_evento_status_processo: string
  data_reservada: string
  melhor_horario_reserva: string
  id_canal_atendimento: string
  id_login: string
  id_contrato: string
  id_estrutura: string
  id_circuito: string
  origem_cadastro: string
  ultima_atualizacao: string
}
